/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useSuspenseQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type { Stamp } from "../twittra.schemas"

import { customReviver } from ".././reviver"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

export type getStampsResponse200 = {
  data: Stamp[]
  status: 200
}

export type getStampsResponse401 = {
  data: void
  status: 401
}

export type getStampsResponse500 = {
  data: void
  status: 500
}

export type getStampsResponseSuccess = (getStampsResponse200) & {
  headers: Headers
}
export type getStampsResponseError =
  & (getStampsResponse401 | getStampsResponse500)
  & {
    headers: Headers
  }

export const getGetStampsUrl = () => {
  return `/api/v1/stamps`
}

export const getStamps = async (
  options?: RequestInit,
): Promise<getStampsResponseSuccess> => {
  const res = await fetch(getGetStampsUrl(), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getStampsResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getStampsResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getStampsResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getStampsResponseSuccess
}

export const getGetStampsQueryKey = () => {
  return [
    `/api/v1/stamps`,
  ] as const
}

export const getGetStampsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStamps>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetStampsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStamps>>> = (
    { signal },
  ) => getStamps({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStamps>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetStampsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStamps>>
>
export type GetStampsSuspenseQueryError = void

export function useGetStampsSuspense<
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStamps>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStampsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export type getStampByIdResponse200 = {
  data: Stamp
  status: 200
}

export type getStampByIdResponse401 = {
  data: void
  status: 401
}

export type getStampByIdResponse500 = {
  data: void
  status: 500
}

export type getStampByIdResponseSuccess = (getStampByIdResponse200) & {
  headers: Headers
}
export type getStampByIdResponseError =
  & (getStampByIdResponse401 | getStampByIdResponse500)
  & {
    headers: Headers
  }

export const getGetStampByIdUrl = (stampId: string) => {
  return `/api/v1/stamps/${stampId}`
}

export const getStampById = async (
  stampId: string,
  options?: RequestInit,
): Promise<getStampByIdResponseSuccess> => {
  const res = await fetch(getGetStampByIdUrl(stampId), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getStampByIdResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getStampByIdResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getStampByIdResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getStampByIdResponseSuccess
}

export const getGetStampByIdQueryKey = (stampId?: string) => {
  return [
    `/api/v1/stamps/${stampId}`,
  ] as const
}

export const getGetStampByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStampById>>,
  TError = void,
>(
  stampId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStampById>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetStampByIdQueryKey(stampId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStampById>>> = (
    { signal },
  ) => getStampById(stampId, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStampById>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetStampByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStampById>>
>
export type GetStampByIdSuspenseQueryError = void

export function useGetStampByIdSuspense<
  TData = Awaited<ReturnType<typeof getStampById>>,
  TError = void,
>(
  stampId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStampById>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStampByIdSuspenseQueryOptions(stampId, options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export type getStampImageResponse401 = {
  data: void
  status: 401
}

export type getStampImageResponse500 = {
  data: void
  status: 500
}
export type getStampImageResponseError =
  & (getStampImageResponse401 | getStampImageResponse500)
  & {
    headers: Headers
  }

export type getStampImageResponse = getStampImageResponseError

export const getGetStampImageUrl = (stampId: string) => {
  return `/api/v1/stamps/${stampId}/image`
}

export const getStampImage = async (
  stampId: string,
  options?: RequestInit,
): Promise<getStampImageResponse> => {
  const res = await fetch(getGetStampImageUrl(stampId), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getStampImageResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getStampImageResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getStampImageResponse["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getStampImageResponse
}

export const getGetStampImageQueryKey = (stampId?: string) => {
  return [
    `/api/v1/stamps/${stampId}/image`,
  ] as const
}

export const getGetStampImageSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStampImage>>,
  TError = void,
>(
  stampId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStampImage>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetStampImageQueryKey(stampId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStampImage>>> = (
    { signal },
  ) => getStampImage(stampId, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStampImage>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetStampImageSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStampImage>>
>
export type GetStampImageSuspenseQueryError = void

export function useGetStampImageSuspense<
  TData = Awaited<ReturnType<typeof getStampImage>>,
  TError = void,
>(
  stampId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getStampImage>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStampImageSuspenseQueryOptions(stampId, options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
