/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useSuspenseQuery } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type { MessageListItem, ReadMessagesRequest } from "../twittra.schemas"

import { customReviver } from ".././reviver"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

export type markMessagesAsReadResponse204 = {
  data: void
  status: 204
}

export type markMessagesAsReadResponse401 = {
  data: void
  status: 401
}

export type markMessagesAsReadResponse500 = {
  data: void
  status: 500
}

export type markMessagesAsReadResponseSuccess =
  & (markMessagesAsReadResponse204)
  & {
    headers: Headers
  }
export type markMessagesAsReadResponseError =
  & (markMessagesAsReadResponse401 | markMessagesAsReadResponse500)
  & {
    headers: Headers
  }

export const getMarkMessagesAsReadUrl = () => {
  return `/api/v1/messages/read`
}

export const markMessagesAsRead = async (
  readMessagesRequest: ReadMessagesRequest,
  options?: RequestInit,
): Promise<markMessagesAsReadResponseSuccess> => {
  const res = await fetch(getMarkMessagesAsReadUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(
      readMessagesRequest,
    ),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: markMessagesAsReadResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: markMessagesAsReadResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: markMessagesAsReadResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as markMessagesAsReadResponseSuccess
}

export const getMarkMessagesAsReadMutationOptions = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markMessagesAsRead>>,
      TError,
      { data: ReadMessagesRequest },
      TContext
    >
    fetch?: RequestInit
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof markMessagesAsRead>>,
  TError,
  { data: ReadMessagesRequest },
  TContext
> => {
  const mutationKey = ["markMessagesAsRead"]
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markMessagesAsRead>>,
    { data: ReadMessagesRequest }
  > = (props) => {
    const { data } = props ?? {}

    return markMessagesAsRead(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MarkMessagesAsReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof markMessagesAsRead>>
>
export type MarkMessagesAsReadMutationBody = ReadMessagesRequest
export type MarkMessagesAsReadMutationError = void

export const useMarkMessagesAsRead = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markMessagesAsRead>>,
      TError,
      { data: ReadMessagesRequest },
      TContext
    >
    fetch?: RequestInit
  },
): UseMutationResult<
  Awaited<ReturnType<typeof markMessagesAsRead>>,
  TError,
  { data: ReadMessagesRequest },
  TContext
> => {
  const mutationOptions = getMarkMessagesAsReadMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * @summary Get a single message by ID.
 */
export type getMessageResponse200 = {
  data: MessageListItem
  status: 200
}

export type getMessageResponse401 = {
  data: void
  status: 401
}

export type getMessageResponse404 = {
  data: void
  status: 404
}

export type getMessageResponse500 = {
  data: void
  status: 500
}

export type getMessageResponseSuccess = (getMessageResponse200) & {
  headers: Headers
}
export type getMessageResponseError =
  & (getMessageResponse401 | getMessageResponse404 | getMessageResponse500)
  & {
    headers: Headers
  }

export const getGetMessageUrl = (messageId: string) => {
  return `/api/v1/messages/${messageId}`
}

export const getMessage = async (
  messageId: string,
  options?: RequestInit,
): Promise<getMessageResponseSuccess> => {
  const res = await fetch(getGetMessageUrl(messageId), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getMessageResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getMessageResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getMessageResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMessageResponseSuccess
}

export const getGetMessageQueryKey = (messageId?: string) => {
  return [
    `/api/v1/messages/${messageId}`,
  ] as const
}

export const getGetMessageSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMessage>>,
  TError = void,
>(
  messageId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMessage>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMessageQueryKey(messageId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessage>>> = (
    { signal },
  ) => getMessage(messageId, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMessage>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetMessageSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMessage>>
>
export type GetMessageSuspenseQueryError = void

/**
 * @summary Get a single message by ID.
 */

export function useGetMessageSuspense<
  TData = Awaited<ReturnType<typeof getMessage>>,
  TError = void,
>(
  messageId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMessage>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMessageSuspenseQueryOptions(messageId, options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export type addMessageStampResponse204 = {
  data: void
  status: 204
}

export type addMessageStampResponse401 = {
  data: void
  status: 401
}

export type addMessageStampResponse500 = {
  data: void
  status: 500
}

export type addMessageStampResponseSuccess = (addMessageStampResponse204) & {
  headers: Headers
}
export type addMessageStampResponseError =
  & (addMessageStampResponse401 | addMessageStampResponse500)
  & {
    headers: Headers
  }

export const getAddMessageStampUrl = (messageId: string, stampId: string) => {
  return `/api/v1/messages/${messageId}/stamps/${stampId}`
}

export const addMessageStamp = async (
  messageId: string,
  stampId: string,
  options?: RequestInit,
): Promise<addMessageStampResponseSuccess> => {
  const res = await fetch(getAddMessageStampUrl(messageId, stampId), {
    ...options,
    method: "POST",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: addMessageStampResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: addMessageStampResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: addMessageStampResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as addMessageStampResponseSuccess
}

export const getAddMessageStampMutationOptions = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addMessageStamp>>,
      TError,
      { messageId: string; stampId: string },
      TContext
    >
    fetch?: RequestInit
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof addMessageStamp>>,
  TError,
  { messageId: string; stampId: string },
  TContext
> => {
  const mutationKey = ["addMessageStamp"]
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addMessageStamp>>,
    { messageId: string; stampId: string }
  > = (props) => {
    const { messageId, stampId } = props ?? {}

    return addMessageStamp(messageId, stampId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AddMessageStampMutationResult = NonNullable<
  Awaited<ReturnType<typeof addMessageStamp>>
>

export type AddMessageStampMutationError = void

export const useAddMessageStamp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addMessageStamp>>,
      TError,
      { messageId: string; stampId: string },
      TContext
    >
    fetch?: RequestInit
  },
): UseMutationResult<
  Awaited<ReturnType<typeof addMessageStamp>>,
  TError,
  { messageId: string; stampId: string },
  TContext
> => {
  const mutationOptions = getAddMessageStampMutationOptions(options)

  return useMutation(mutationOptions)
}
export type removeMessageStampResponse204 = {
  data: void
  status: 204
}

export type removeMessageStampResponse401 = {
  data: void
  status: 401
}

export type removeMessageStampResponse500 = {
  data: void
  status: 500
}

export type removeMessageStampResponseSuccess =
  & (removeMessageStampResponse204)
  & {
    headers: Headers
  }
export type removeMessageStampResponseError =
  & (removeMessageStampResponse401 | removeMessageStampResponse500)
  & {
    headers: Headers
  }

export const getRemoveMessageStampUrl = (
  messageId: string,
  stampId: string,
) => {
  return `/api/v1/messages/${messageId}/stamps/${stampId}`
}

export const removeMessageStamp = async (
  messageId: string,
  stampId: string,
  options?: RequestInit,
): Promise<removeMessageStampResponseSuccess> => {
  const res = await fetch(getRemoveMessageStampUrl(messageId, stampId), {
    ...options,
    method: "DELETE",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: removeMessageStampResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: removeMessageStampResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: removeMessageStampResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as removeMessageStampResponseSuccess
}

export const getRemoveMessageStampMutationOptions = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeMessageStamp>>,
      TError,
      { messageId: string; stampId: string },
      TContext
    >
    fetch?: RequestInit
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof removeMessageStamp>>,
  TError,
  { messageId: string; stampId: string },
  TContext
> => {
  const mutationKey = ["removeMessageStamp"]
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeMessageStamp>>,
    { messageId: string; stampId: string }
  > = (props) => {
    const { messageId, stampId } = props ?? {}

    return removeMessageStamp(messageId, stampId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoveMessageStampMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeMessageStamp>>
>

export type RemoveMessageStampMutationError = void

export const useRemoveMessageStamp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeMessageStamp>>,
      TError,
      { messageId: string; stampId: string },
      TContext
    >
    fetch?: RequestInit
  },
): UseMutationResult<
  Awaited<ReturnType<typeof removeMessageStamp>>,
  TError,
  { messageId: string; stampId: string },
  TContext
> => {
  const mutationOptions = getRemoveMessageStampMutationOptions(options)

  return useMutation(mutationOptions)
}
