/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useSuspenseQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type { Message } from "../twittra.schemas"

import { customReviver } from ".././reviver"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

/**
 * @summary Get messages for the timeline.
 */
export type getTimelineResponse200 = {
  data: Message[]
  status: 200
}

export type getTimelineResponse401 = {
  data: void
  status: 401
}

export type getTimelineResponse500 = {
  data: void
  status: 500
}

export type getTimelineResponseSuccess = (getTimelineResponse200) & {
  headers: Headers
}
export type getTimelineResponseError =
  & (getTimelineResponse401 | getTimelineResponse500)
  & {
    headers: Headers
  }

export const getGetTimelineUrl = () => {
  return `/api/v1/timeline`
}

export const getTimeline = async (
  options?: RequestInit,
): Promise<getTimelineResponseSuccess> => {
  const res = await fetch(getGetTimelineUrl(), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getTimelineResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getTimelineResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getTimelineResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getTimelineResponseSuccess
}

export const getGetTimelineQueryKey = () => {
  return [
    `/api/v1/timeline`,
  ] as const
}

export const getGetTimelineSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getTimeline>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getTimeline>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetTimelineQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimeline>>> = (
    { signal },
  ) => getTimeline({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getTimeline>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetTimelineSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTimeline>>
>
export type GetTimelineSuspenseQueryError = void

/**
 * @summary Get messages for the timeline.
 */

export function useGetTimelineSuspense<
  TData = Awaited<ReturnType<typeof getTimeline>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getTimeline>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTimelineSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
