/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { delay, http, HttpResponse } from "msw"
import type { RequestHandlerOptions } from "msw"

export const getOauthCallbackMockHandler = (
  overrideResponse?:
    | unknown
    | ((
      info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get("*/auth/callback", async (info) => {
    await delay(100)
    if (typeof overrideResponse === "function") await overrideResponse(info)
    return new HttpResponse(null, { status: 200 })
  }, options)
}

export const getLoginMockHandler = (
  overrideResponse?:
    | unknown
    | ((
      info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get("*/auth/login", async (info) => {
    await delay(100)
    if (typeof overrideResponse === "function") await overrideResponse(info)
    return new HttpResponse(null, { status: 200 })
  }, options)
}
export const getAuthMock = () => [
  getOauthCallbackMockHandler(),
  getLoginMockHandler(),
]
