/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useSuspenseQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type { OauthCallbackParams } from "../twittra.schemas"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

/**
 * @summary Handle the OAuth2 callback.
 */
export type oauthCallbackResponse302 = {
  data: void
  status: 302
}

export type oauthCallbackResponse400 = {
  data: void
  status: 400
}

export type oauthCallbackResponse401 = {
  data: void
  status: 401
}

export type oauthCallbackResponse500 = {
  data: void
  status: 500
}
export type oauthCallbackResponseError =
  & (
    | oauthCallbackResponse302
    | oauthCallbackResponse400
    | oauthCallbackResponse401
    | oauthCallbackResponse500
  )
  & {
    headers: Headers
  }

export type oauthCallbackResponse = oauthCallbackResponseError

export const getOauthCallbackUrl = (params: OauthCallbackParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/auth/callback?${stringifiedParams}`
    : `/api/v1/auth/callback`
}

export const oauthCallback = async (
  params: OauthCallbackParams,
  options?: RequestInit,
): Promise<oauthCallbackResponse> => {
  const res = await fetch(getOauthCallbackUrl(params), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: oauthCallbackResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: oauthCallbackResponseError["data"] = body
      ? JSON.parse(body)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: oauthCallbackResponse["data"] = body ? JSON.parse(body) : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as oauthCallbackResponse
}

export const getOauthCallbackQueryKey = (params?: OauthCallbackParams) => {
  return [
    `/api/v1/auth/callback`,
    ...(params ? [params] : []),
  ] as const
}

export const getOauthCallbackSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof oauthCallback>>,
  TError = void,
>(
  params: OauthCallbackParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof oauthCallback>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getOauthCallbackQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof oauthCallback>>> = (
    { signal },
  ) => oauthCallback(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof oauthCallback>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type OauthCallbackSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof oauthCallback>>
>
export type OauthCallbackSuspenseQueryError = void

/**
 * @summary Handle the OAuth2 callback.
 */

export function useOauthCallbackSuspense<
  TData = Awaited<ReturnType<typeof oauthCallback>>,
  TError = void,
>(
  params: OauthCallbackParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof oauthCallback>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getOauthCallbackSuspenseQueryOptions(params, options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Start the OAuth2 login process by redirecting to the authorization URL.
 */
export type loginResponse302 = {
  data: void
  status: 302
}

export type loginResponse500 = {
  data: void
  status: 500
}
export type loginResponseError = (loginResponse302 | loginResponse500) & {
  headers: Headers
}

export type loginResponse = loginResponseError

export const getLoginUrl = () => {
  return `/api/v1/auth/login`
}

export const login = async (options?: RequestInit): Promise<loginResponse> => {
  const res = await fetch(getLoginUrl(), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: loginResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: loginResponseError["data"] = body ? JSON.parse(body) : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: loginResponse["data"] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}

export const getLoginQueryKey = () => {
  return [
    `/api/v1/auth/login`,
  ] as const
}

export const getLoginSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof login>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getLoginQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof login>>> = (
    { signal },
  ) => login({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>
    & { queryKey: QueryKey }
}

export type LoginSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>
export type LoginSuspenseQueryError = void

/**
 * @summary Start the OAuth2 login process by redirecting to the authorization URL.
 */

export function useLoginSuspense<
  TData = Awaited<ReturnType<typeof login>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getLoginSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
