/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useSuspenseQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type { User } from "../twittra.schemas"

import { customReviver } from ".././reviver"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

/**
 * @summary Get the current authenticated user's information.
 */
export type getMeResponse200 = {
  data: User
  status: 200
}

export type getMeResponse401 = {
  data: void
  status: 401
}

export type getMeResponse500 = {
  data: void
  status: 500
}

export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers
}
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers
}

export const getGetMeUrl = () => {
  return `/api/v1/me`
}

export const getMe = async (
  options?: RequestInit,
): Promise<getMeResponseSuccess> => {
  const res = await fetch(getGetMeUrl(), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getMeResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getMeResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getMeResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMeResponseSuccess
}

export const getGetMeQueryKey = () => {
  return [
    `/api/v1/me`,
  ] as const
}

export const getGetMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMe>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = (
    { signal },
  ) => getMe({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    & { queryKey: QueryKey }
}

export type GetMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMe>>
>
export type GetMeSuspenseQueryError = void

/**
 * @summary Get the current authenticated user's information.
 */

export function useGetMeSuspense<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMe>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get a user's information by user ID.
 */
export type getUserByIdResponse200 = {
  data: User
  status: 200
}

export type getUserByIdResponse401 = {
  data: void
  status: 401
}

export type getUserByIdResponse500 = {
  data: void
  status: 500
}

export type getUserByIdResponseSuccess = (getUserByIdResponse200) & {
  headers: Headers
}
export type getUserByIdResponseError =
  & (getUserByIdResponse401 | getUserByIdResponse500)
  & {
    headers: Headers
  }

export const getGetUserByIdUrl = (userId: string) => {
  return `/api/v1/users/${userId}`
}

export const getUserById = async (
  userId: string,
  options?: RequestInit,
): Promise<getUserByIdResponseSuccess> => {
  const res = await fetch(getGetUserByIdUrl(userId), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getUserByIdResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getUserByIdResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getUserByIdResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserByIdResponseSuccess
}

export const getGetUserByIdQueryKey = (userId?: string) => {
  return [
    `/api/v1/users/${userId}`,
  ] as const
}

export const getGetUserByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = void,
>(
  userId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUserById>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(userId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = (
    { signal },
  ) => getUserById(userId, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUserById>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetUserByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>
export type GetUserByIdSuspenseQueryError = void

/**
 * @summary Get a user's information by user ID.
 */

export function useGetUserByIdSuspense<
  TData = Awaited<ReturnType<typeof getUserById>>,
  TError = void,
>(
  userId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUserById>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserByIdSuspenseQueryOptions(userId, options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Get a user's icon by user ID.
 */
export type getUserIconResponse401 = {
  data: void
  status: 401
}

export type getUserIconResponse500 = {
  data: void
  status: 500
}
export type getUserIconResponseError =
  & (getUserIconResponse401 | getUserIconResponse500)
  & {
    headers: Headers
  }

export type getUserIconResponse = getUserIconResponseError

export const getGetUserIconUrl = (userId: string) => {
  return `/api/v1/users/${userId}/icon`
}

export const getUserIcon = async (
  userId: string,
  options?: RequestInit,
): Promise<getUserIconResponse> => {
  const res = await fetch(getGetUserIconUrl(userId), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getUserIconResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getUserIconResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getUserIconResponse["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserIconResponse
}

export const getGetUserIconQueryKey = (userId?: string) => {
  return [
    `/api/v1/users/${userId}/icon`,
  ] as const
}

export const getGetUserIconSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserIcon>>,
  TError = void,
>(
  userId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUserIcon>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserIconQueryKey(userId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserIcon>>> = (
    { signal },
  ) => getUserIcon(userId, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUserIcon>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetUserIconSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserIcon>>
>
export type GetUserIconSuspenseQueryError = void

/**
 * @summary Get a user's icon by user ID.
 */

export function useGetUserIconSuspense<
  TData = Awaited<ReturnType<typeof getUserIcon>>,
  TError = void,
>(
  userId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUserIcon>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserIconSuspenseQueryOptions(userId, options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
