/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useSuspenseQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type { User } from "../twittra.schemas"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

/**
 * @summary Get the current authenticated user's information.
 */
export const getGetMeUrl = () => {
  return `/api/v1/me`
}

export const getMe = async (options?: RequestInit): Promise<User> => {
  const res = await fetch(getGetMeUrl(), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: User = body ? JSON.parse(body) : {}
  return data
}

export const getGetMeQueryKey = () => {
  return [
    `/api/v1/me`,
  ] as const
}

export const getGetMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMe>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = (
    { signal },
  ) => getMe({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    & { queryKey: QueryKey }
}

export type GetMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMe>>
>
export type GetMeSuspenseQueryError = void

/**
 * @summary Get the current authenticated user's information.
 */

export function useGetMeSuspense<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = void,
>(
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMe>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
