/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker"

import { delay, http, HttpResponse } from "msw"
import type { RequestHandlerOptions } from "msw"

import type { User } from "../twittra.schemas"

export const getGetMeResponseMock = (
  overrideResponse: Partial<User> = {},
): User => ({
  displayName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  handle: faker.string.alpha({ length: { min: 10, max: 32 } }),
  id: faker.string.uuid(),
  ...overrideResponse,
})

export const getGetUserByIdResponseMock = (
  overrideResponse: Partial<User> = {},
): User => ({
  displayName: faker.string.alpha({ length: { min: 10, max: 20 } }),
  handle: faker.string.alpha({ length: { min: 10, max: 32 } }),
  id: faker.string.uuid(),
  ...overrideResponse,
})

export const getGetMeMockHandler = (
  overrideResponse?:
    | User
    | ((
      info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.get("*/me", async (info) => {
    await delay(100)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? (typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse)
          : getGetMeResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    )
  }, options)
}

export const getGetUserByIdMockHandler = (
  overrideResponse?:
    | User
    | ((
      info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.get("*/users/:userId", async (info) => {
    await delay(100)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? (typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse)
          : getGetUserByIdResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    )
  }, options)
}

export const getGetUserIconMockHandler = (
  overrideResponse?:
    | unknown
    | ((
      info: Parameters<Parameters<typeof http.get>[1]>[0],
    ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get("*/users/:userId/icon", async (info) => {
    await delay(100)
    if (typeof overrideResponse === "function") await overrideResponse(info)
    return new HttpResponse(null, { status: 200 })
  }, options)
}
export const getUserMock = () => [
  getGetMeMockHandler(),
  getGetUserByIdMockHandler(),
  getGetUserIconMockHandler(),
]
