/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
import { useSuspenseQuery } from "@tanstack/react-query"
import type {
  QueryFunction,
  QueryKey,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"

import type {
  GetChannelMessagesParams,
  MessageListItem,
} from "../twittra.schemas"

import { customReviver } from ".././reviver"

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

/**
 * @summary Get messages from a specific channel.
 */
export type getChannelMessagesResponse200 = {
  data: MessageListItem[]
  status: 200
}

export type getChannelMessagesResponse401 = {
  data: void
  status: 401
}

export type getChannelMessagesResponse500 = {
  data: void
  status: 500
}

export type getChannelMessagesResponseSuccess =
  & (getChannelMessagesResponse200)
  & {
    headers: Headers
  }
export type getChannelMessagesResponseError =
  & (getChannelMessagesResponse401 | getChannelMessagesResponse500)
  & {
    headers: Headers
  }

export const getGetChannelMessagesUrl = (
  channelId: string,
  params?: GetChannelMessagesParams,
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(
        key,
        value === null
          ? "null"
          : value instanceof Date
          ? value.toISOString()
          : value.toString(),
      )
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/channels/${channelId}/messages?${stringifiedParams}`
    : `/api/v1/channels/${channelId}/messages`
}

export const getChannelMessages = async (
  channelId: string,
  params?: GetChannelMessagesParams,
  options?: RequestInit,
): Promise<getChannelMessagesResponseSuccess> => {
  const res = await fetch(getGetChannelMessagesUrl(channelId, params), {
    ...options,
    method: "GET",
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  if (!res.ok) {
    const err: globalThis.Error & {
      info?: getChannelMessagesResponseError["data"]
      status?: number
    } = new globalThis.Error()
    const data: getChannelMessagesResponseError["data"] = body
      ? JSON.parse(body, customReviver)
      : {}
    err.info = data
    err.status = res.status
    throw err
  }
  const data: getChannelMessagesResponseSuccess["data"] = body
    ? JSON.parse(body, customReviver)
    : {}
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getChannelMessagesResponseSuccess
}

export const getGetChannelMessagesQueryKey = (
  channelId?: string,
  params?: GetChannelMessagesParams,
) => {
  return [
    `/api/v1/channels/${channelId}/messages`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetChannelMessagesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getChannelMessages>>,
  TError = void,
>(
  channelId: string,
  params?: GetChannelMessagesParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getChannelMessages>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ??
    getGetChannelMessagesQueryKey(channelId, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannelMessages>>> =
    ({ signal }) =>
      getChannelMessages(channelId, params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as
    & UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getChannelMessages>>,
      TError,
      TData
    >
    & { queryKey: QueryKey }
}

export type GetChannelMessagesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChannelMessages>>
>
export type GetChannelMessagesSuspenseQueryError = void

/**
 * @summary Get messages from a specific channel.
 */

export function useGetChannelMessagesSuspense<
  TData = Awaited<ReturnType<typeof getChannelMessages>>,
  TError = void,
>(
  channelId: string,
  params?: GetChannelMessagesParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getChannelMessages>>,
      TError,
      TData
    >
    fetch?: RequestInit
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetChannelMessagesSuspenseQueryOptions(
    channelId,
    params,
    options,
  )

  const query = useSuspenseQuery(queryOptions) as
    & UseSuspenseQueryResult<TData, TError>
    & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}
