/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// BotState : BOT状態 0: 停止 1: 有効 2: 一時停止
/// BOT状態 0: 停止 1: 有効 2: 一時停止
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum BotState {
    deactivated = 0,
    active = 1,
    suspended = 2,
}

impl std::fmt::Display for BotState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::deactivated => "0",
                Self::active => "1",
                Self::suspended => "2",
            }
        )
    }
}
impl Default for BotState {
    fn default() -> BotState {
        Self::deactivated
    }
}
