/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChannelEventDetail : イベント内容
/// イベント内容
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChannelEventDetail {
    TopicChangedEvent(Box<models::TopicChangedEvent>),
    SubscribersChangedEvent(Box<models::SubscribersChangedEvent>),
    PinAddedEvent(Box<models::PinAddedEvent>),
    PinRemovedEvent(Box<models::PinRemovedEvent>),
    NameChangedEvent(Box<models::NameChangedEvent>),
    ParentChangedEvent(Box<models::ParentChangedEvent>),
    VisibilityChangedEvent(Box<models::VisibilityChangedEvent>),
    ForcedNotificationChangedEvent(Box<models::ForcedNotificationChangedEvent>),
    ChildCreatedEvent(Box<models::ChildCreatedEvent>),
}

impl Default for ChannelEventDetail {
    fn default() -> Self {
        Self::TopicChangedEvent(Default::default())
    }
}
