/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChannelViewState : 閲覧状態
/// 閲覧状態
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelViewState {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "stale_viewing")]
    StaleViewing,
    #[serde(rename = "monitoring")]
    Monitoring,
    #[serde(rename = "editing")]
    Editing,
}

impl std::fmt::Display for ChannelViewState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::StaleViewing => write!(f, "stale_viewing"),
            Self::Monitoring => write!(f, "monitoring"),
            Self::Editing => write!(f, "editing"),
        }
    }
}

impl Default for ChannelViewState {
    fn default() -> ChannelViewState {
        Self::None
    }
}
