/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClippedMessage : クリップされたメッセージ
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClippedMessage {
    #[serde(rename = "message")]
    pub message: Box<models::Message>,
    /// クリップした日時
    #[serde(rename = "clippedAt")]
    pub clipped_at: String,
}

impl ClippedMessage {
    /// クリップされたメッセージ
    pub fn new(message: models::Message, clipped_at: String) -> ClippedMessage {
        ClippedMessage {
            message: Box::new(message),
            clipped_at,
        }
    }
}
