/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBot200Response {
    Bot(Box<models::Bot>),
    BotDetail(Box<models::BotDetail>),
}

impl Default for GetBot200Response {
    fn default() -> Self {
        Self::Bot(Default::default())
    }
}
