/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClient200Response {
    OAuth2Client(Box<models::OAuth2Client>),
    OAuth2ClientDetail(Box<models::OAuth2ClientDetail>),
}

impl Default for GetClient200Response {
    fn default() -> Self {
        Self::OAuth2Client(Default::default())
    }
}
