/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MyChannelViewState : 自身のチャンネル閲覧状態
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MyChannelViewState {
    /// WSセッションの識別子
    #[serde(rename = "key")]
    pub key: String,
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: uuid::Uuid,
    #[serde(rename = "state")]
    pub state: models::ChannelViewState,
}

impl MyChannelViewState {
    /// 自身のチャンネル閲覧状態
    pub fn new(
        key: String,
        channel_id: uuid::Uuid,
        state: models::ChannelViewState,
    ) -> MyChannelViewState {
        MyChannelViewState {
            key,
            channel_id,
            state,
        }
    }
}
