/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuth2Scope : OAuth2スコープ
/// OAuth2スコープ
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OAuth2Scope {
    #[serde(rename = "openid")]
    Openid,
    #[serde(rename = "profile")]
    Profile,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "manage_bot")]
    ManageBot,
}

impl std::fmt::Display for OAuth2Scope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Openid => write!(f, "openid"),
            Self::Profile => write!(f, "profile"),
            Self::Read => write!(f, "read"),
            Self::Write => write!(f, "write"),
            Self::ManageBot => write!(f, "manage_bot"),
        }
    }
}

impl Default for OAuth2Scope {
    fn default() -> OAuth2Scope {
        Self::Openid
    }
}
