/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostStarRequest : スター追加リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostStarRequest {
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: uuid::Uuid,
}

impl PostStarRequest {
    /// スター追加リクエスト
    pub fn new(channel_id: uuid::Uuid) -> PostStarRequest {
        PostStarRequest { channel_id }
    }
}
