/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostBotActionLeaveRequest : BOTチャンネル退出リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostBotActionLeaveRequest {
    /// チャンネルUUID
    #[serde(rename = "channelId")]
    pub channel_id: uuid::Uuid,
}

impl PostBotActionLeaveRequest {
    /// BOTチャンネル退出リクエスト
    pub fn new(channel_id: uuid::Uuid) -> PostBotActionLeaveRequest {
        PostBotActionLeaveRequest { channel_id }
    }
}
