/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutChannelSubscribeLevelRequest : チャンネル購読レベル変更リクエスト
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutChannelSubscribeLevelRequest {
    #[serde(rename = "level")]
    pub level: models::ChannelSubscribeLevel,
}

impl PutChannelSubscribeLevelRequest {
    /// チャンネル購読レベル変更リクエスト
    pub fn new(level: models::ChannelSubscribeLevel) -> PutChannelSubscribeLevelRequest {
        PutChannelSubscribeLevelRequest { level }
    }
}
