/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QallRoomStateChangedEvent : Qallのルーム状態が変更された
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QallRoomStateChangedEvent {
    #[serde(rename = "roomStates")]
    pub room_states: Vec<models::QallRoomStateChangedEventRoomStatesInner>,
}

impl QallRoomStateChangedEvent {
    /// Qallのルーム状態が変更された
    pub fn new(
        room_states: Vec<models::QallRoomStateChangedEventRoomStatesInner>,
    ) -> QallRoomStateChangedEvent {
        QallRoomStateChangedEvent { room_states }
    }
}
