/*
 * traQ v3
 *
 * traQ v3 API
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThumbnailType : サムネイル画像のタイプ
/// サムネイル画像のタイプ
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ThumbnailType {
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "waveform")]
    Waveform,
}

impl std::fmt::Display for ThumbnailType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Image => write!(f, "image"),
            Self::Waveform => write!(f, "waveform"),
        }
    }
}

impl Default for ThumbnailType {
    fn default() -> ThumbnailType {
        Self::Image
    }
}
