/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
export interface MessageListItem {
  channelId: string
  content: string
  createdAt: Date
  id: string
  reactions: Reaction[]
  updatedAt: Date
  /** The user who posted the message.
Omitted if the server hasn't cached the user info. */
  user?: User
  userId: string
}

/**
 * Payload for the messagesUpdated event
 */
export interface MessagesUpdatedPayload {
  messages: MessageListItem[]
}

export interface Reaction {
  stampCount: number
  stampId: string
  userId: string
}

export type ServerEventOneOfType =
  typeof ServerEventOneOfType[keyof typeof ServerEventOneOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerEventOneOfType = {
  messagesUpdated: "messagesUpdated",
} as const

export type ServerEventOneOf = {
  payload: MessagesUpdatedPayload
  type: ServerEventOneOfType
}

/**
 * Discriminated union of all Socket.io server-to-client events
 */
export type ServerEvent = ServerEventOneOf

export interface Stamp {
  id: string
  /** @maxLength 32 */
  name: string
}

export interface User {
  displayName: string
  /** @maxLength 32 */
  handle: string
  id: string
}

export type OauthCallbackParams = {
  /**
   * The authorization code returned by the OAuth2 provider.
   */
  code: string
  /**
   * The CSRF state returned by the OAuth2 provider.
   */
  state: string
}

export type GetStampsParams = {
  /**
   * Filter stamps by name
   */
  name?: string
}
