/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
export interface MessageListItem {
  channelId: string
  content: string
  createdAt: Date
  id: string
  reactions: Reaction[]
  updatedAt: Date
  /** The user who posted the message.
Omitted if the server hasn't cached the user info. */
  user?: User
  userId: string
}

export interface Reaction {
  stampCount: number
  stampId: string
  userId: string
}

export interface User {
  displayName: string
  handle: string
  id: string
}

export type OauthCallbackParams = {
  /**
   * The authorization code returned by the OAuth2 provider.
   */
  code: string
  /**
   * The CSRF state returned by the OAuth2 provider.
   */
  state: string
}
