/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twittra
 * OpenAPI spec version: 0.1.0
 */
export interface User {
  displayName: string
  handle: string
  id: string
}

export type OauthCallbackParams = {
  /**
   * The authorization code returned by the OAuth2 provider.
   */
  code: string
  /**
   * The CSRF state returned by the OAuth2 provider.
   */
  state: string
}
